//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotal_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PaymentID { get; set; }
        public Nullable<int> BookingID { get; set; }
        public Nullable<int> PaymentTypeID { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
        public Nullable<int> IsActive { get; set; }
    }
}
